[package]
name = "public_ip"
version = "0.1.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"

[dependencies]
log = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "*"
trust-dns-client = "0.20"
tokio = "1"
url = "2"
